'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class ValidationResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Core.ValidationResource", GetType(ValidationResource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System.Reflection
        '''Imports System.Web
        '''
        '''Namespace ConstantCore
        '''    &apos;&apos;&apos; &lt;summary&gt;
        '''    &apos;&apos;&apos; 共通番号
        '''    &apos;&apos;&apos; &lt;/summary&gt;
        '''    Public Module Consts
        '''        &apos;&apos;&apos; &lt;summary&gt;
        '''        &apos;&apos;&apos; セッションキークラス
        '''        &apos;&apos;&apos; &lt;/summary&gt;
        '''        Public Class SessionKey
        '''            Public Shared LOGIN_INFO As String = &quot;LoginInfo_new&quot;
        '''        End Class
        '''
        '''        &apos;&apos;&apos; &lt;summary&gt;
        '''        &apos;&apos;&apos; 画面ID
        '''        &apos;&apos;&apos; &lt;/summary&gt;
        '''        Public Class ScreenId
        '''            &apos;&apos;&apos; &lt;summary&gt;
        '''            &apos;&apos;&apos; ログイン画面
        '''            &apos;&apos;&apos; &lt;/summ [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property Consts() As String
            Get
                Return ResourceManager.GetString("Consts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_001() As String
            Get
                Return ResourceManager.GetString("MSG_001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_002() As String
            Get
                Return ResourceManager.GetString("MSG_002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}を登録します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_003() As String
            Get
                Return ResourceManager.GetString("MSG_003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}を削除します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_004() As String
            Get
                Return ResourceManager.GetString("MSG_004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}を登録しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_005() As String
            Get
                Return ResourceManager.GetString("MSG_005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}を削除しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_006() As String
            Get
                Return ResourceManager.GetString("MSG_006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to データ更新処理で例外が発生しました。&lt;br /&gt;再度処理を実行してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_007() As String
            Get
                Return ResourceManager.GetString("MSG_007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 他のユーザーに更新されました。&lt;br /&gt;画面を閉じ、再度処理を実行してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_008() As String
            Get
                Return ResourceManager.GetString("MSG_008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索できる日付は{0}以内です。.
        '''</summary>
        Public Shared ReadOnly Property MSG_009() As String
            Get
                Return ResourceManager.GetString("MSG_009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索条件に沿った{0}がありません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_010() As String
            Get
                Return ResourceManager.GetString("MSG_010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索条件に沿った{0}CSVを出力します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_011() As String
            Get
                Return ResourceManager.GetString("MSG_011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象行を選択してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_012() As String
            Get
                Return ResourceManager.GetString("MSG_012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象行は1行まで選択できます。.
        '''</summary>
        Public Shared ReadOnly Property MSG_013() As String
            Get
                Return ResourceManager.GetString("MSG_013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}を出力します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_014() As String
            Get
                Return ResourceManager.GetString("MSG_014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}処理を実行します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_015() As String
            Get
                Return ResourceManager.GetString("MSG_015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}処理が完了しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_016() As String
            Get
                Return ResourceManager.GetString("MSG_016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の{0}において、{1}処理が実行されているため、&lt;br /&gt;{2}は削除できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_017() As String
            Get
                Return ResourceManager.GetString("MSG_017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ユーザーIDを入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_018() As String
            Get
                Return ResourceManager.GetString("MSG_018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to パスワードを入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_019() As String
            Get
                Return ResourceManager.GetString("MSG_019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ユーザーIDまたはパスワードに誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_020() As String
            Get
                Return ResourceManager.GetString("MSG_020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to システムを利用できないユーザーです。&lt;br /&gt;
        '''管理者に問合せしてください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_021() As String
            Get
                Return ResourceManager.GetString("MSG_021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 取引不可の得意先は選択できません。&lt;br /&gt;
        '''管理者に問合せしてください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_022() As String
            Get
                Return ResourceManager.GetString("MSG_022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 他のユーザーに更新されました。&lt;br /&gt;
        '''画面を閉じ、再度処理を実行してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_023() As String
            Get
                Return ResourceManager.GetString("MSG_023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売上が入力済みのため、内外区分に未定は登録できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_024() As String
            Get
                Return ResourceManager.GetString("MSG_024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売上金額より小さい受注金額は入力できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_025() As String
            Get
                Return ResourceManager.GetString("MSG_025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 発注日を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_026() As String
            Get
                Return ResourceManager.GetString("MSG_026", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 開始と終了の大小関係に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_027() As String
            Get
                Return ResourceManager.GetString("MSG_027", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索できる日付は12か月以内です。.
        '''</summary>
        Public Shared ReadOnly Property MSG_028() As String
            Get
                Return ResourceManager.GetString("MSG_028", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索条件に沿った外注発注情報がありません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_029() As String
            Get
                Return ResourceManager.GetString("MSG_029", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索条件に沿った支払予定明細書情報がありません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_030() As String
            Get
                Return ResourceManager.GetString("MSG_030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 支払予定明細書を出力します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_031() As String
            Get
                Return ResourceManager.GetString("MSG_031", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 買掛締処理が行われていないため、帳票出力できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_032() As String
            Get
                Return ResourceManager.GetString("MSG_032", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 買掛金集計表を出力します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_033() As String
            Get
                Return ResourceManager.GetString("MSG_033", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売掛締処理が行われていないため、帳票出力できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_034() As String
            Get
                Return ResourceManager.GetString("MSG_034", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売掛金元帳を出力します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_035() As String
            Get
                Return ResourceManager.GetString("MSG_035", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(制作)の作業に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_036() As String
            Get
                Return ResourceManager.GetString("MSG_036", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(制作)の必須項目が未入力の行があります。&lt;br /&gt;
        '''(内外・作業・数量・単価・金額).
        '''</summary>
        Public Shared ReadOnly Property MSG_037() As String
            Get
                Return ResourceManager.GetString("MSG_037", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(製版・デジタル印刷)の作業に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_038() As String
            Get
                Return ResourceManager.GetString("MSG_038", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(製版・デジタル印刷)の部品に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_039() As String
            Get
                Return ResourceManager.GetString("MSG_039", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(製版・デジタル印刷)の必須項目が未入力の行があります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_040() As String
            Get
                Return ResourceManager.GetString("MSG_040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(刷版)の部品に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_041() As String
            Get
                Return ResourceManager.GetString("MSG_041", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(刷版)の作業に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_042() As String
            Get
                Return ResourceManager.GetString("MSG_042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(刷版)のサイズに誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_043() As String
            Get
                Return ResourceManager.GetString("MSG_043", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(刷版)の必須項目が未入力の行があります。&lt;br /&gt;
        '''(内外・部品・頁数・作業・サイズ・面付・&lt;br /&gt;
        ''' 台数・単価・金額).
        '''</summary>
        Public Shared ReadOnly Property MSG_044() As String
            Get
                Return ResourceManager.GetString("MSG_044", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(印刷)の機種に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_045() As String
            Get
                Return ResourceManager.GetString("MSG_045", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(印刷)の必須項目が未入力の行があります。&lt;br /&gt;
        '''(内外・機種・通し数・計算区分・単価・金額).
        '''</summary>
        Public Shared ReadOnly Property MSG_046() As String
            Get
                Return ResourceManager.GetString("MSG_046", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(加工)の作業に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_047() As String
            Get
                Return ResourceManager.GetString("MSG_047", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(加工)のサイズに誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_048() As String
            Get
                Return ResourceManager.GetString("MSG_048", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(加工)の必須項目が未入力の行があります。&lt;br /&gt;
        '''(内外・作業・サイズ・数量・単価・金額).
        '''</summary>
        Public Shared ReadOnly Property MSG_049() As String
            Get
                Return ResourceManager.GetString("MSG_049", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(用紙)の部品に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_050() As String
            Get
                Return ResourceManager.GetString("MSG_050", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(用紙)の銘柄に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_051() As String
            Get
                Return ResourceManager.GetString("MSG_051", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(用紙)の必須項目が未入力の行があります。&lt;br /&gt;
        '''(当/先・部品・銘柄・規格・縦・横・&lt;br /&gt;
        ''' R/S・連量・単位区分・数量・数量合計・単価・金額).
        '''</summary>
        Public Shared ReadOnly Property MSG_052() As String
            Get
                Return ResourceManager.GetString("MSG_052", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(その他)の作業に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_053() As String
            Get
                Return ResourceManager.GetString("MSG_053", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(その他)の必須項目が未入力の行があります。&lt;br /&gt;
        '''(内外・作業・数量・単価・金額).
        '''</summary>
        Public Shared ReadOnly Property MSG_054() As String
            Get
                Return ResourceManager.GetString("MSG_054", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(製版・デジタル印刷)で選択できる部品は工程(刷版)と&lt;br /&gt;
        '''同じでなければなりません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_055() As String
            Get
                Return ResourceManager.GetString("MSG_055", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工程(加工)で選択できる部品は工程(刷版)と同じでなければなりません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_056() As String
            Get
                Return ResourceManager.GetString("MSG_056", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 品名を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_057() As String
            Get
                Return ResourceManager.GetString("MSG_057", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 得意先を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_058() As String
            Get
                Return ResourceManager.GetString("MSG_058", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 担当を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_059() As String
            Get
                Return ResourceManager.GetString("MSG_059", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注日を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_060() As String
            Get
                Return ResourceManager.GetString("MSG_060", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 納品日を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_061() As String
            Get
                Return ResourceManager.GetString("MSG_061", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注金額を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_062() As String
            Get
                Return ResourceManager.GetString("MSG_062", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 得意先に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_063() As String
            Get
                Return ResourceManager.GetString("MSG_063", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 担当に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_064() As String
            Get
                Return ResourceManager.GetString("MSG_064", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注日と納品日の大小関係に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_065() As String
            Get
                Return ResourceManager.GetString("MSG_065", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注日と検収日の大小関係に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_066() As String
            Get
                Return ResourceManager.GetString("MSG_066", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 製品サイズ(縦・横)を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_067() As String
            Get
                Return ResourceManager.GetString("MSG_067", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注金額と明細金額が一致していません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_068() As String
            Get
                Return ResourceManager.GetString("MSG_068", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注金額の桁数を超過しています。(9桁).
        '''</summary>
        Public Shared ReadOnly Property MSG_069() As String
            Get
                Return ResourceManager.GetString("MSG_069", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 明細金額の桁数を超過しています。(9桁).
        '''</summary>
        Public Shared ReadOnly Property MSG_070() As String
            Get
                Return ResourceManager.GetString("MSG_070", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 明細仕切金額の桁数を超過しています。(9桁).
        '''</summary>
        Public Shared ReadOnly Property MSG_071() As String
            Get
                Return ResourceManager.GetString("MSG_071", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象日を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_072() As String
            Get
                Return ResourceManager.GetString("MSG_072", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 発注担当を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_073() As String
            Get
                Return ResourceManager.GetString("MSG_073", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 発注先を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_074() As String
            Get
                Return ResourceManager.GetString("MSG_074", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 納期を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_075() As String
            Get
                Return ResourceManager.GetString("MSG_075", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 発注担当に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_076() As String
            Get
                Return ResourceManager.GetString("MSG_076", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 発注先に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_077() As String
            Get
                Return ResourceManager.GetString("MSG_077", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 納入先に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_078() As String
            Get
                Return ResourceManager.GetString("MSG_078", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 納期時刻はHHMM形式で入力してください。&lt;br /&gt;
        '''例. 12:30の場合、1230.
        '''</summary>
        Public Shared ReadOnly Property MSG_079() As String
            Get
                Return ResourceManager.GetString("MSG_079", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 外注発注の明細を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_080() As String
            Get
                Return ResourceManager.GetString("MSG_080", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 作業を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_081() As String
            Get
                Return ResourceManager.GetString("MSG_081", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 作業名を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_082() As String
            Get
                Return ResourceManager.GetString("MSG_082", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 発注金額を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_083() As String
            Get
                Return ResourceManager.GetString("MSG_083", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 合計金額は999,999,999を超えることはできません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_084() As String
            Get
                Return ResourceManager.GetString("MSG_084", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 取引不可の発注先は選択できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_085() As String
            Get
                Return ResourceManager.GetString("MSG_085", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 取引不可の納入先は選択できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_086() As String
            Get
                Return ResourceManager.GetString("MSG_086", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 外注発注書を出力します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_087() As String
            Get
                Return ResourceManager.GetString("MSG_087", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 同じコードのデータが既に存在しています。.
        '''</summary>
        Public Shared ReadOnly Property MSG_088() As String
            Get
                Return ResourceManager.GetString("MSG_088", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to コードの桁数は{0}桁で入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_089() As String
            Get
                Return ResourceManager.GetString("MSG_089", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 外注発注情報を登録しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_090() As String
            Get
                Return ResourceManager.GetString("MSG_090", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 仕入が完了した外注発注のため、外注発注情報を更新できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_091() As String
            Get
                Return ResourceManager.GetString("MSG_091", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 外注発注情報を登録します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_092() As String
            Get
                Return ResourceManager.GetString("MSG_092", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の外注発注において、仕入情報が既に登録されているため、&lt;br /&gt;
        '''外注発注登録は削除できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_093() As String
            Get
                Return ResourceManager.GetString("MSG_093", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 外注発注情報を削除します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_094() As String
            Get
                Return ResourceManager.GetString("MSG_094", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 外注発注情報を削除しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_095() As String
            Get
                Return ResourceManager.GetString("MSG_095", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to コード情報を登録しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_096() As String
            Get
                Return ResourceManager.GetString("MSG_096", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to このコードは変更不可のコードのため、削除できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_097() As String
            Get
                Return ResourceManager.GetString("MSG_097", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to コード情報を削除しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_098() As String
            Get
                Return ResourceManager.GetString("MSG_098", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 入力内容を登録します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_099() As String
            Get
                Return ResourceManager.GetString("MSG_099", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 用紙発注の明細を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_100() As String
            Get
                Return ResourceManager.GetString("MSG_100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の用紙発注において、仕入情報が既に登録されているため、&lt;br /&gt;
        '''用紙発注登録は変更できません。&lt;br /&gt;
        '''仕入情報を削除してから再度処理を実行してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_101() As String
            Get
                Return ResourceManager.GetString("MSG_101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 銘柄を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_102() As String
            Get
                Return ResourceManager.GetString("MSG_102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 連量を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_103() As String
            Get
                Return ResourceManager.GetString("MSG_103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 厚さを入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_104() As String
            Get
                Return ResourceManager.GetString("MSG_104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 数量を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_105() As String
            Get
                Return ResourceManager.GetString("MSG_105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 単価を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_106() As String
            Get
                Return ResourceManager.GetString("MSG_106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 金額を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_107() As String
            Get
                Return ResourceManager.GetString("MSG_107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 倉庫を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_108() As String
            Get
                Return ResourceManager.GetString("MSG_108", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 銘柄に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_109() As String
            Get
                Return ResourceManager.GetString("MSG_109", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 断数を選択してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_110() As String
            Get
                Return ResourceManager.GetString("MSG_110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 寸法(縦横)を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_111() As String
            Get
                Return ResourceManager.GetString("MSG_111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 数量は999,999,999.999を超えることはできません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_112() As String
            Get
                Return ResourceManager.GetString("MSG_112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 搬入時刻はHHMM形式で入力してください。&lt;br /&gt;
        '''例. 12:30の場合、1230.
        '''</summary>
        Public Shared ReadOnly Property MSG_113() As String
            Get
                Return ResourceManager.GetString("MSG_113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 選択した規格がコードマスタに存在しない　または　マスタの内容に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_114() As String
            Get
                Return ResourceManager.GetString("MSG_114", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 仕入日を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_115() As String
            Get
                Return ResourceManager.GetString("MSG_115", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 外注仕入の明細を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_116() As String
            Get
                Return ResourceManager.GetString("MSG_116", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 税率を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_117() As String
            Get
                Return ResourceManager.GetString("MSG_117", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 外注発注金額を超える外注仕入登録はできません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_118() As String
            Get
                Return ResourceManager.GetString("MSG_118", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 外注仕入情報を登録します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_119() As String
            Get
                Return ResourceManager.GetString("MSG_119", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 外注仕入情報を登録しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_120() As String
            Get
                Return ResourceManager.GetString("MSG_120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 外注仕入情報を削除します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_121() As String
            Get
                Return ResourceManager.GetString("MSG_121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 外注仕入情報を削除しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_122() As String
            Get
                Return ResourceManager.GetString("MSG_122", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の仕入日において、買掛締処理が実行されているため、&lt;br /&gt;
        '''外注仕入情報は登録できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_123() As String
            Get
                Return ResourceManager.GetString("MSG_123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の仕入日において、買掛締処理が実行されているため、&lt;br /&gt;
        '''外注仕入情報は削除できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_124() As String
            Get
                Return ResourceManager.GetString("MSG_124", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の外注発注が削除されています。&lt;br /&gt;
        '''再度処理を実行してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_125() As String
            Get
                Return ResourceManager.GetString("MSG_125", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の得意先は準備処理が完了しています。&lt;br /&gt;
        '''再度準備処理を行う場合、該当の得意先の準備処理を&lt;br /&gt;
        '''解除してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_126() As String
            Get
                Return ResourceManager.GetString("MSG_126", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の得意先は準備処理が完了していないため、&apos;解除ができません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_127() As String
            Get
                Return ResourceManager.GetString("MSG_127", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 入力した請求締日が存在しません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_128() As String
            Get
                Return ResourceManager.GetString("MSG_128", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 請求締処理が未処理の締日の場合、帳票は出力できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_129() As String
            Get
                Return ResourceManager.GetString("MSG_129", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to データが取得できませんでした。.
        '''</summary>
        Public Shared ReadOnly Property MSG_130() As String
            Get
                Return ResourceManager.GetString("MSG_130", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 用紙発注情報を登録します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_131() As String
            Get
                Return ResourceManager.GetString("MSG_131", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 用紙発注情報を登録しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_132() As String
            Get
                Return ResourceManager.GetString("MSG_132", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の支払日において、買掛締処理が実行されているため、&lt;br /&gt;支払情報は登録できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_133() As String
            Get
                Return ResourceManager.GetString("MSG_133", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 用紙発注情報を削除します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_134() As String
            Get
                Return ResourceManager.GetString("MSG_134", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 用紙発注情報をボディ部に反映します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_135() As String
            Get
                Return ResourceManager.GetString("MSG_135", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ボディ部に反映しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_136() As String
            Get
                Return ResourceManager.GetString("MSG_136", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 用紙発注情報をボディ部から削除します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_137() As String
            Get
                Return ResourceManager.GetString("MSG_137", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 用紙発注情報の明細を削除しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_138() As String
            Get
                Return ResourceManager.GetString("MSG_138", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 入力内容をクリアしてよろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_139() As String
            Get
                Return ResourceManager.GetString("MSG_139", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 用紙発注情報を削除しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_140() As String
            Get
                Return ResourceManager.GetString("MSG_140", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の得意先はすでに登録されています。.
        '''</summary>
        Public Shared ReadOnly Property MSG_141() As String
            Get
                Return ResourceManager.GetString("MSG_141", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の得意先は、締め日が異なるため、追加できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_142() As String
            Get
                Return ResourceManager.GetString("MSG_142", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 選択した得意先を明細から削除しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_143() As String
            Get
                Return ResourceManager.GetString("MSG_143", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 請求締準備処理が{0}しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_144() As String
            Get
                Return ResourceManager.GetString("MSG_144", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 入力した取引先が存在しません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_145() As String
            Get
                Return ResourceManager.GetString("MSG_145", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}はハイフン(-)を含めて入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_146() As String
            Get
                Return ResourceManager.GetString("MSG_146", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}に入力できる数値は01～31です。.
        '''</summary>
        Public Shared ReadOnly Property MSG_147() As String
            Get
                Return ResourceManager.GetString("MSG_147", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 同じ名称・支店名・略称のデータが既に存在しています。.
        '''</summary>
        Public Shared ReadOnly Property MSG_148() As String
            Get
                Return ResourceManager.GetString("MSG_148", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売掛締処理 - 締処理が完了しました。&lt;br /&gt; 売掛締月を翌月に繰越しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_149() As String
            Get
                Return ResourceManager.GetString("MSG_149", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売掛締処理 - 準備解除処理が完了しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_150() As String
            Get
                Return ResourceManager.GetString("MSG_150", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売掛締処理 - 準備処理が完了しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_151() As String
            Get
                Return ResourceManager.GetString("MSG_151", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 締月は準備処理が完了しています。&lt;br /&gt; 再度準備処理を行う場合、準備処理を解除してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_152() As String
            Get
                Return ResourceManager.GetString("MSG_152", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 締月は準備処理が完了していません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_153() As String
            Get
                Return ResourceManager.GetString("MSG_153", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 締月は準備処理が完了していません。&lt;br /&gt; 準備処理が完了してから、締処理を実行してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_154() As String
            Get
                Return ResourceManager.GetString("MSG_154", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 用紙仕入対象の行がありません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_155() As String
            Get
                Return ResourceManager.GetString("MSG_155", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の仕入日において、買掛締処理が実行されているため、&lt;br /&gt;用紙仕入情報は登録できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_156() As String
            Get
                Return ResourceManager.GetString("MSG_156", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の仕入日において、買掛締処理が実行されているため、&lt;br /&gt;用紙仕入情報は削除できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_157() As String
            Get
                Return ResourceManager.GetString("MSG_157", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の用紙発注が削除されています。&lt;br /&gt;再度処理を実行してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_158() As String
            Get
                Return ResourceManager.GetString("MSG_158", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 仕入先を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_159() As String
            Get
                Return ResourceManager.GetString("MSG_159", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 支払日を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_160() As String
            Get
                Return ResourceManager.GetString("MSG_160", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索条件に沿った支払情報がありません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_161() As String
            Get
                Return ResourceManager.GetString("MSG_161", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 支払情報を削除しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_162() As String
            Get
                Return ResourceManager.GetString("MSG_162", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 入力内容を削除します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_163() As String
            Get
                Return ResourceManager.GetString("MSG_163", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 支払情報を登録しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_164() As String
            Get
                Return ResourceManager.GetString("MSG_164", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 発注先が2つ以上選択されています。.
        '''</summary>
        Public Shared ReadOnly Property MSG_165() As String
            Get
                Return ResourceManager.GetString("MSG_165", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の入金日において、{0}処理が実行されているため、&lt;br /&gt; 入金情報は登録できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_166() As String
            Get
                Return ResourceManager.GetString("MSG_166", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 入金情報を{0}しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_167() As String
            Get
                Return ResourceManager.GetString("MSG_167", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 選択した発注の用紙仕入登録を行います。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_168() As String
            Get
                Return ResourceManager.GetString("MSG_168", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to このコードは変更不可のコードのため、更新できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_169() As String
            Get
                Return ResourceManager.GetString("MSG_169", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 発注日または仕入日を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_170() As String
            Get
                Return ResourceManager.GetString("MSG_170", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索条件で発注先が未指定のため、納入依頼書を出力できません。&lt;br /&gt;
        '''検索条件で発注先を指定して再検索してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_171() As String
            Get
                Return ResourceManager.GetString("MSG_171", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索条件に沿った外注仕入情報がありません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_172() As String
            Get
                Return ResourceManager.GetString("MSG_172", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の仕入先は準備処理が完了しています。&lt;br /&gt;再度準備処理を行う場合、該当の仕入先の準備処理を解除してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_173() As String
            Get
                Return ResourceManager.GetString("MSG_173", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の仕入先は準備処理が完了していないため、解除できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_174() As String
            Get
                Return ResourceManager.GetString("MSG_174", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索条件で倉庫が未指定のため、納入予定表を出力できません。&lt;br/&gt;検索条件で倉庫を指定して再検索してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_175() As String
            Get
                Return ResourceManager.GetString("MSG_175", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の締日は準備処理が完了していないため、解除できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_176() As String
            Get
                Return ResourceManager.GetString("MSG_176", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索条件に沿った用紙仕入情報がありません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_177() As String
            Get
                Return ResourceManager.GetString("MSG_177", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 同じ銘柄名・品種・メーカーのデータが既に存在しています。.
        '''</summary>
        Public Shared ReadOnly Property MSG_178() As String
            Get
                Return ResourceManager.GetString("MSG_178", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索条件に沿った用紙発注情報がありません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_179() As String
            Get
                Return ResourceManager.GetString("MSG_179", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 用紙情報を削除しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_180() As String
            Get
                Return ResourceManager.GetString("MSG_180", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 用紙情報を登録しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_181() As String
            Get
                Return ResourceManager.GetString("MSG_181", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 一括仕入できる行数は最大100行です。.
        '''</summary>
        Public Shared ReadOnly Property MSG_182() As String
            Get
                Return ResourceManager.GetString("MSG_182", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 選択した発注の納入依頼書を出力します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_183() As String
            Get
                Return ResourceManager.GetString("MSG_183", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 選択した発注の納入予定表を出力します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_184() As String
            Get
                Return ResourceManager.GetString("MSG_184", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 得意先と受注担当のいずれかを入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_185() As String
            Get
                Return ResourceManager.GetString("MSG_185", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索条件に沿った売上情報がありません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_186() As String
            Get
                Return ResourceManager.GetString("MSG_186", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to スケジュール登録画面を起動する前に受注情報を登録します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_187() As String
            Get
                Return ResourceManager.GetString("MSG_187", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注情報を登録しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_188() As String
            Get
                Return ResourceManager.GetString("MSG_188", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to データ更新処理で例外が発生しました。&lt;br /&gt;再度処理を実行してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_189() As String
            Get
                Return ResourceManager.GetString("MSG_189", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注情報を登録します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_190() As String
            Get
                Return ResourceManager.GetString("MSG_190", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注情報を削除しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_191() As String
            Get
                Return ResourceManager.GetString("MSG_191", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 完納済みの受注のため、受注情報を更新できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_192() As String
            Get
                Return ResourceManager.GetString("MSG_192", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 他のユーザーに更新されました。&lt;br /&gt; 画面を閉じ、再度処理を実行してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_193() As String
            Get
                Return ResourceManager.GetString("MSG_193", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注に対する発注が入力済みのため、&lt;br /&gt; 受注情報は削除できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_194() As String
            Get
                Return ResourceManager.GetString("MSG_194", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注に対する売上が入力済みのため、&lt;br /&gt; 受注情報は削除できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_195() As String
            Get
                Return ResourceManager.GetString("MSG_195", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注情報を削除します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_196() As String
            Get
                Return ResourceManager.GetString("MSG_196", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注伝票を出力します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_197() As String
            Get
                Return ResourceManager.GetString("MSG_197", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索条件に沿った受注情報がありません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_198() As String
            Get
                Return ResourceManager.GetString("MSG_198", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}を出力します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_199() As String
            Get
                Return ResourceManager.GetString("MSG_199", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 通し数の大小関係に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_200() As String
            Get
                Return ResourceManager.GetString("MSG_200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 同じ原価単価情報が既に登録されています。.
        '''</summary>
        Public Shared ReadOnly Property MSG_201() As String
            Get
                Return ResourceManager.GetString("MSG_201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の得意先の締日は{0}処理が完了しているため、{1}できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_202() As String
            Get
                Return ResourceManager.GetString("MSG_202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 選択した得意先を明細から削除しますか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_203() As String
            Get
                Return ResourceManager.GetString("MSG_203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売上を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_204() As String
            Get
                Return ResourceManager.GetString("MSG_204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注金額を超えた売上金額は入力できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_205() As String
            Get
                Return ResourceManager.GetString("MSG_205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 内訳は5つまで入力できます。.
        '''</summary>
        Public Shared ReadOnly Property MSG_206() As String
            Get
                Return ResourceManager.GetString("MSG_206", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の請求日において、請求締処理が実行されているため、&lt;br /&gt;売上情報は登録できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_207() As String
            Get
                Return ResourceManager.GetString("MSG_207", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象の売上日において、売掛締処理が実行されているため、&lt;br /&gt;売上情報は登録できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_208() As String
            Get
                Return ResourceManager.GetString("MSG_208", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売上情報を削除しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_209() As String
            Get
                Return ResourceManager.GetString("MSG_209", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の締日は準備処理が完了しています。&lt;br /&gt; 再度準備処理を行う場合、準備処理を解除してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_210() As String
            Get
                Return ResourceManager.GetString("MSG_210", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の締日は準備処理が完了していません。&lt;br /&gt; 準備処理が完了してから、締処理を実行してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_211() As String
            Get
                Return ResourceManager.GetString("MSG_211", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の締日は準備処理が完了しています。&lt;br /&gt; 再度準備処理を行う場合、該当の得意先の準備処理を解除してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_212() As String
            Get
                Return ResourceManager.GetString("MSG_212", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 請求締準備処理を実行します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_213() As String
            Get
                Return ResourceManager.GetString("MSG_213", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 取引区分を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_214() As String
            Get
                Return ResourceManager.GetString("MSG_214", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 支払金額を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_215() As String
            Get
                Return ResourceManager.GetString("MSG_215", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 手形内訳に誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_216() As String
            Get
                Return ResourceManager.GetString("MSG_216", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 手形期日を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_217() As String
            Get
                Return ResourceManager.GetString("MSG_217", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 請求締準備処理を解除します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_218() As String
            Get
                Return ResourceManager.GetString("MSG_218", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の得意先は準備処理が完了していないため、解除ができません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_219() As String
            Get
                Return ResourceManager.GetString("MSG_219", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当の締日は準備処理が完了しているため、削除できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_220() As String
            Get
                Return ResourceManager.GetString("MSG_220", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売上内訳情報を削除しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_221() As String
            Get
                Return ResourceManager.GetString("MSG_221", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売上金額は999,999,999を超えることはできません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_222() As String
            Get
                Return ResourceManager.GetString("MSG_222", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 合計は999,999,999を超えることはできません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_223() As String
            Get
                Return ResourceManager.GetString("MSG_223", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売上金額と内訳の合計金額が不一致です。.
        '''</summary>
        Public Shared ReadOnly Property MSG_224() As String
            Get
                Return ResourceManager.GetString("MSG_224", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 更新対象のデータがありません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_225() As String
            Get
                Return ResourceManager.GetString("MSG_225", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 他のユーザーによって請求締処理または請求締解除処理が実行されました。&lt;br /&gt; 画面を閉じ、再度処理を実行してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_226() As String
            Get
                Return ResourceManager.GetString("MSG_226", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売上情報を登録しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_227() As String
            Get
                Return ResourceManager.GetString("MSG_227", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 取込ファイルが未選択です。.
        '''</summary>
        Public Shared ReadOnly Property MSG_228() As String
            Get
                Return ResourceManager.GetString("MSG_228", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ファイル形式に誤りがあります。CSVファイルのみ取込できます。.
        '''</summary>
        Public Shared ReadOnly Property MSG_229() As String
            Get
                Return ResourceManager.GetString("MSG_229", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSVの文字コードにSJIS以外が指定されています。.
        '''</summary>
        Public Shared ReadOnly Property MSG_230() As String
            Get
                Return ResourceManager.GetString("MSG_230", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to レコードの項目数が4以外の行があります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_231() As String
            Get
                Return ResourceManager.GetString("MSG_231", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 取込対象のレコードがありません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_232() As String
            Get
                Return ResourceManager.GetString("MSG_232", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSVファイル内に重複した受注番号が存在します。.
        '''</summary>
        Public Shared ReadOnly Property MSG_233() As String
            Get
                Return ResourceManager.GetString("MSG_233", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1列目：受注番号を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_234() As String
            Get
                Return ResourceManager.GetString("MSG_234", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2列目：工程を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_235() As String
            Get
                Return ResourceManager.GetString("MSG_235", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3列目：原価区分を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_236() As String
            Get
                Return ResourceManager.GetString("MSG_236", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4列目：原価を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_237() As String
            Get
                Return ResourceManager.GetString("MSG_237", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 指定した原価に数値以外の値が入力されています。({0}行).
        '''</summary>
        Public Shared ReadOnly Property MSG_238() As String
            Get
                Return ResourceManager.GetString("MSG_238", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 存在しない受注番号が指定されています。({0}行).
        '''</summary>
        Public Shared ReadOnly Property MSG_239() As String
            Get
                Return ResourceManager.GetString("MSG_239", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 指定した工程に誤りがあります。({0}行).
        '''</summary>
        Public Shared ReadOnly Property MSG_240() As String
            Get
                Return ResourceManager.GetString("MSG_240", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 指定した原価区分に誤りがあります。({0}行).
        '''</summary>
        Public Shared ReadOnly Property MSG_241() As String
            Get
                Return ResourceManager.GetString("MSG_241", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注番号：{0}の製造原価がマイナスとなりました。&lt;br /&gt; 
        '''取込できません。({1}行).
        '''</summary>
        Public Shared ReadOnly Property MSG_242() As String
            Get
                Return ResourceManager.GetString("MSG_242", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 受注番号：{0}の製造原価が999,999,999を&lt;br /&gt; 
        '''超えたため、取込できません。({1}行).
        '''</summary>
        Public Shared ReadOnly Property MSG_243() As String
            Get
                Return ResourceManager.GetString("MSG_243", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 原価データを取込します。よろしいですか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_244() As String
            Get
                Return ResourceManager.GetString("MSG_244", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 原価データ取込が完了しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_245() As String
            Get
                Return ResourceManager.GetString("MSG_245", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 請求書編集の明細は25明細まで入力できます。.
        '''</summary>
        Public Shared ReadOnly Property MSG_246() As String
            Get
                Return ResourceManager.GetString("MSG_246", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 内訳を選択した場合は、売上金額を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_247() As String
            Get
                Return ResourceManager.GetString("MSG_247", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 内訳を選択してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_248() As String
            Get
                Return ResourceManager.GetString("MSG_248", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 内訳・品名・売上金額を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_249() As String
            Get
                Return ResourceManager.GetString("MSG_249", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 請求情報が全て印字しないになっています。.
        '''</summary>
        Public Shared ReadOnly Property MSG_250() As String
            Get
                Return ResourceManager.GetString("MSG_250", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 請求金額と明細合計金額が一致していません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_251() As String
            Get
                Return ResourceManager.GetString("MSG_251", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}が存在する行は削除できません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_252() As String
            Get
                Return ResourceManager.GetString("MSG_252", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 入力内容をボディ部から削除しますか？.
        '''</summary>
        Public Shared ReadOnly Property MSG_253() As String
            Get
                Return ResourceManager.GetString("MSG_253", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 請求書編集情報を登録しました。.
        '''</summary>
        Public Shared ReadOnly Property MSG_254() As String
            Get
                Return ResourceManager.GetString("MSG_254", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 作業コードに誤りがあります。.
        '''</summary>
        Public Shared ReadOnly Property MSG_255() As String
            Get
                Return ResourceManager.GetString("MSG_255", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 指定した請求書番号の請求書が存在しません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_256() As String
            Get
                Return ResourceManager.GetString("MSG_256", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 売上日を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_257() As String
            Get
                Return ResourceManager.GetString("MSG_257", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 既に削除された発注情報です。外注発注検索画面でデータの再検索を行ってください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_258() As String
            Get
                Return ResourceManager.GetString("MSG_258", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 既に削除された受注情報です。受注検索画面でデータの再検索を行ってください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_259() As String
            Get
                Return ResourceManager.GetString("MSG_259", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 既に削除された受注情報です。外注発注検索画面でデータの再検索を行ってください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_260() As String
            Get
                Return ResourceManager.GetString("MSG_260", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 既に削除された仕入情報です。外注仕入検索画面でデータの再検索を行ってください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_261() As String
            Get
                Return ResourceManager.GetString("MSG_261", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 既に削除された発注情報です。用紙発注検索画面でデータの再検索を行ってください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_262() As String
            Get
                Return ResourceManager.GetString("MSG_262", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 既に削除された仕入情報です。用紙仕入検索画面でデータの再検索を行ってください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_263() As String
            Get
                Return ResourceManager.GetString("MSG_263", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 搬入日を入力してください。.
        '''</summary>
        Public Shared ReadOnly Property MSG_264() As String
            Get
                Return ResourceManager.GetString("MSG_264", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to 金額は999,999,999を超えることはできません。.
        '''</summary>
        Public Shared ReadOnly Property MSG_265() As String
            Get
                Return ResourceManager.GetString("MSG_265", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property MSG_266() As String
            Get
                Return ResourceManager.GetString("MSG_266", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property MSG_267() As String
            Get
                Return ResourceManager.GetString("MSG_267", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property MSG_268() As String
            Get
                Return ResourceManager.GetString("MSG_268", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property MSG_269() As String
            Get
                Return ResourceManager.GetString("MSG_269", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property MSG_270() As String
            Get
                Return ResourceManager.GetString("MSG_270", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
